### ISSUE TITLE
Converter Sartet erst garnicht. 

### ISSUE THREAD

**Issue by OberstRudel** [yankee42/courseplay-osm-converter#10]
Ich habe die version 1.05 auf Modhoster geladen. und wenn ich die jar datei öffnen klicke passiert nix . Habe Win 10 und Java auch aktuell. Weis nicht wie ich es zum laufen bringen kann.auch doppelklick bringt nix.MFG

**Comment by yankee42** [comment]
Irgendetwas müsste da eigentlich schon passieren. Entweder das Programm sollte aufgehen oder es müsste irgend eine Meldung kommen, dass der Dateityp unbekannt ist oder etwas in der Art. Ist es eventuell im Hintergrund gestartet? Ist in der Taskleiste etwas zu sehen?

Ansonsten öffne mal ein command-prompt (Strg+R, dann `cmd`), gehe dann mit `cd c:\pfad\wo\du\das\jar\gespeichert\hast` in das entsprechende Verzeichnis und dann führe dann `java -jar courseconvert.jar` aus. Das ist das Gleiche was eigentlich automatisch passiert, wenn du die Datei doppelt klickst, aber dann müsste auf jeden Fall Feedback kommen.

**Comment by OberstRudel** [comment]
Feuerwehr.... So gut kenne ich mich mit PC net  aus. Wenn ich die jar Datei doppelt klicke blinkt nur es  mal kurz in der Taskleiste was auf. Wenn ich es richtig sehe sieht es aus wie das Fenster von der Eingabeaufforderung. Das passiet alles in einer sekunde, danch passiert nix mehr. Kommt auch keine Fehlermeldung oder Irgenwas. MFG

**Comment by OberstRudel** [comment]
okay nochmal versucht. mit der eingabeaufforderung habe ich es zum laufen bekommen. warum geht es nicht normal?? haben sie eventuell eine Idee??
mfg

**Comment by yankee42** [comment]
Das deutet darauf hin, dass mit der Java-Installation etwas nicht stimmt. Du kannst versuchen Java neu zu installieren. Eine weitere Möglichkeit wäre das Freeware-Programm [Jarfix](http://johann.loefflmann.net/en/software/jarfix/index.html), welches je nach Ursache das Problem auch beheben könnte.
