### ISSUE TITLE
Konvertierung zu OSM startet garnicht!

### ISSUE THREAD

**Issue by calli181102** [yankee42/courseplay-osm-converter#11]
Hallo lieber Yankee,

Ich habe mir das Tool heute auch mal heruntergeladen, weil ich in Zukunft schneller meine Kurse anpassen wollte. 

Leider funktioniert dies aber nicht wie gewollt. Ich starte den Converter wähle die benötigte coursemanager.xml aus und gebe der Datei einen Namen.

Danach passiert aber nichts mehr. Es wird keine Datei erstellt und eine Fehlermeldung kommt auch nicht.

Nun ist meine Frage ob in der Coursemanager.xml irgendetwas fehlerhaft sein kann.
Ich habe gestern einen Fehler beim erstellen von Ordnern gemacht. Deshalb musste ich die Datein im Courseplay Ordner neu sortieren. 
Deshalb habe ich alle ID's neu gemacht.

Das funktioniert auch wieder super ingame alles so wie vorher auch und ohne Fehlermeldungen.
Leider scheint dein Converter die Datei jetzt aber nicht mehr zu erkennen.

Meine Courseplay-Version: 6.01.00210
Meine OSM-Converter_Version: 1.05

Mein CourseplayCourses - Ordner:
[FS_19Kandelin.SampleModMap.zip](https://github.com/yankee42/courseplay-osm-converter/files/3158372/FS_19Kandelin.SampleModMap.zip)

**Comment by yankee42** [comment]
Ich habe dein ZIP bei mir extrahiert und die courseManager.xml konvertiert und es funktionierte ganz normal. Es hat nur ca. 5 Sekunden gedauert...

Es muss eigentlich schon irgend eine Meldung kommen. Entweder eine Meldung, dass die Konvertierung abgeschlossen ist (mit nochmal der erzeugten Datei) oder eine Fehlermeldung. Das kann natürlich ein paar Sekunden dauern.

Nachdem du die Konvertierung gestartet hast und ein paar Sekunden gewartet hast: Hast du eine hohe CPU-Auslastung? Lässt sich die Benutzeroberfläche noch bedienen (e.g. kannst du nochmal auf konvertieren klicken und erhälst den normalen Dialog?)

**Comment by calli181102** [comment]
Danke erstmal für die schnelle Rückmeldung.
Also ich habe mir deinen Konverter nochmal heruntergeladen.
Dann habe ich nochmals versucht die Kurse zu convertieren. Leider wieder ohne Erfolg auch nach längerem warten. 

Ich hab eine höhere CPU-Auslastung beobachtet, diese fällt jedoch wieder relativ schnell ab und bleibt dann bei 0%. Ich kann die Oberfläche weiterhin bedienen aber nur noch ein oder zweimal danach hängt sie sich auf.

Ich habe dennoch irgendwie das Gefühl, dass eine Datei erstellt wird, da sich der Desktop aktualisiert (kurze Zeit später), aber eben nicht da wo ich angegeben habe. 

Kannst du mir vielleicht nochmal Schritt für Schritt sagen wie du es gemacht hast, da es ja bei dir funktioniert hat.

**Comment by yankee42** [comment]
Wenn der Vorgang abgeschlossen ist, dann soll da eine Meldung wie diese kommen:
![Screenshot file created](https://user-images.githubusercontent.com/1841729/57600122-339d5980-7559-11e9-8401-5a9fb4480c26.png)
Wie man sieht steht da dann nochmal der gesamte Pfad der erzeugten Datei.

So wie ich dich verstehe kommt diese Meldung aber nicht. Und es kommt auch keine Fehlermeldung. Und die Abwesenheit höher CPU-Auslastung deutet auch darauf hin, dass der Konverter in keiner Schleife steckt. Das Programm wartet also auf irgendwas. Aber worauf?

Ich habe hier mal eine Version gebastelt, die Logausgaben generiert. Versuch es doch mal damit und poste die Logausgabe (im Zweifel reichen die letzten paar Zeilen). Das gibt vielleicht ein Hinweis darauf wo das Programm stecken bleibt.

[courseconvert.zip](https://github.com/yankee42/courseplay-osm-converter/files/3171612/courseconvert.zip)

**Comment by xerion8300** [comment]
Ich habe mir die Aktuelle Version herunter geladen aber wenn ich es Starte Ausführen mit Java blinkt kurz ein Schwarzes Fenster auf und das wars.

**Comment by yankee42** [comment]
Komisch. Ich habe das Ticket total vergessen, sorry. Ist das Problem noch aktuell? Könntest du einmal das Programm auf der Konsole manuell mit `java -jar courseconvert.jar` starten?

Dafür unter Windows auf das Startmenü klicken, dann einfach `cmd` tippen, `Enter` drücken und per `cd c:\wo\auch\immer\du\die\Anwendung\gespeichert\hast` und dann obiges Kommando. Dann sollte das Fenster nicht einfach zu gehen, sondern offenbleiben und man sieht ggf. eine Fehlermeldung.

**Comment by xerion8300** [comment]
Thema hat sich erledigt. Habe es hin bekommen.
Aber trotzdem Danke. Mann kann ja mal was vergessen.
Ist nicht so schlimm.
