### ISSUE TITLE
Geänderte Daten werden nicht gespeichert

### ISSUE THREAD

**Issue by stamer85** [yankee42/courseplay-osm-converter#14]
Hallo und danke für das Programm, das bei mir leider nicht geht :-(

Ich hab folgendes Problem:

Ich öffne die courseconvert.jar (neueste Version) und wenn ich dort dann z.B. eine Map konvertieren will, dann gehe ich die Schritte wie beschrieben durch und zum Schluss sagt er mir auch nach kurzer Rechenzeit, dass die .png und die .cal unter Pfad x erstellt wurden (Files created: ...), aber wenn ich dann den Ordner öffne, dann ist da nichts.
Ich habe es schon auf zig Wege versucht:
- mit Admin-Rechten
- mit verschiedenen Einstellungen der Schreibrechte (sogar Vollzugriff für "JEDER")
- in verschiedenen Ordnern auf C:, D:, E: (extern)
- mit Administrator-Konto
Immer wieder das selbe Ergebnis: keine Dateien erstellt (auch nicht "versteckt").

Kurios ist aber, dass mir die courseconvert.jar bei der Suche nach Dateien auch die neu erstellten Dateien zeigt - aber auch nur die courseconvert.jar, nicht aber zum Beispiel die Suche im JOSM.

Ich nutze Win 8.1 auf dem aktuellen Stand, auch alle genutzen Tools sind aktuell...

Für Hilfe wäre ich sehr dankbar...

MfG Jan

![Unbenannt2](https://user-images.githubusercontent.com/57228032/67962881-096e4f80-fbfe-11e9-854a-af7c9e3c1a77.JPG)

**Comment by stamer85** [comment]
So, nach weiterem Testen und rumprobieren konnte ich den Fehler selber beheben:

Ich Idiot habe alles ausgeychlossen, nur mein Comodo nicht. Die Anwendung courseconvert.jar wurde immer nur im Container ausgeführt und lief da drin einwandfrei, nur es konnten keine Dateien aus dem Container raus erstellt werden...

Also für alle, die ein ähnliches Problem haben - checkt mal eure Anti-Viren Programme ;-)

MfG Jan

**Comment by yankee42** [comment]
OK, danke für die Info.
