### ISSUE TITLE
Wie kann man in JOSM alle Tracks bis auf einen ausblenden?

### ISSUE THREAD

**Issue by VatriXxX** [yankee42/courseplay-osm-converter#15]
Aloha, da das alles mit dem Converter jetzt funktioniert, hab ich jetzt eine Frage. Ich weiß zwar nicht ob ich mit der hier richtig bin, aber vielleicht weißt du das @yankee42 
Ist es möglich im OSM nur einzelne Strecken anzeigen zu lassen und die anderen auszublenden?
Denn es sind jetzt gefühlt schon 5 Strecken an bestimmten Punkten Übereinander und da steigt man nicht mehr durch.

**Comment by yankee42** [comment]
Ja, das geht. Also das einfachste ist es natürlich erstmal den Track zu selectieren. Dafür einfach auf eine Linie klicken (nicht den Punkt). Dann wir die schön rot hervorgehoben und man kann die gut erkennen. Wenn das nicht reicht, dann geht folgendes:

![filter-guide](https://user-images.githubusercontent.com/1841729/68090081-fbc00080-fe6f-11e9-9032-08f08f839622.png)

In Worten:
1. Das Filter-Fenster aktivieren (falls nicht schon da)
2. Einen Track selektieren und dann denn Dateinamen kopieren
3. Im Filterpanel auf "Hinzufügen" gehen
4. Das kopierte "filename=xxx" einfügen
5. Filter anwenden
6. Die Kontrollkästchen E (enabled), H (hidden) und I (inverse) aktivieren.
