### ISSUE TITLE
ausführen...???

### ISSUE THREAD

**Issue by funcarfreak** [yankee42/courseplay-osm-converter#16]
Hi, ich glaube ich werde zu alt um mich noch so durch die Daten zu fummeln...
du schreibst: JAR-Datei herunterladen, speichern und ausführen.
WO finde ich eine Datei zum ausführen??? Ich lade courseconvert.jar runter, Doppelklick > öffnet sich RAR > entpacken nach... gemacht! gehe ich nun in den entpackten Ordner finde ich nirgends eine ausführbare Datei. 4 Ordner und die CAL.Datei...
Was mache ich falsch?
Danke
MfG Daniel

**Comment by yankee42** [comment]
Die JAR-Datei IST die Datei zum Ausführen. Du brauchst nichts zu entpacken.

JAR ist eine spezielle zip-Datei, die von der JVM (Java Virtual Machine) ausgeführt werden kann. Da es AUCH eine zip-Datei ist kann man es zwar mit einem entsprechenden Dekompressionsprogramm öffnen, aber das ist nicht das Ziel.

Normalerweise, wenn man die JVM installiert hat, wird beim Doppelklick auf die Datei diese mit der JVM geöffnet und ausgeführt.

Ist java bei dir installiert? Falls nein, dann runterladen auf https://java.com. Falls ja schau mal nach ob du rechte Maustaste auf die Datei machen kannst und dann "öffnen mit" und dort die Möglichkeit hast Java oder JVM auszuwählen. Oder du kannst eine Textdatei mit dem Inhalt `java -jar courseconvert.jar` erstellen und direkt neben der Jar-Datei also "courseconvert.bat" speichern. Doppelt drauf klicken sollte dann eine Konsole öffnen die Java startet.

**Comment by funcarfreak** [comment]
Vielen Dank, hat geklappt...
