### ISSUE TITLE
Unbekannter Fehler bei Konvertierung in osm

### ISSUE THREAD

**Issue by mxalbert** [yankee42/courseplay-osm-converter#3]
![image](https://user-images.githubusercontent.com/38127488/55495463-3abd7780-563d-11e9-968d-10af84c133a1.png)

Hi, dieser Fehler kommt bei mir, wenn ich versuche meine Courseplay Kurse von der Felsbrunn in osm zu konvertieren. Ich konnte die *.xml auswählen, ich konnte einen Namen für eine *.OSM Datei auswählen und einen Speicherort, aber beim klick auf 'öffnen' in dem Menü kommt der Fehler.

**Comment by yankee42** [comment]
Welche Datei hast du ausgewählt? Es muss die `courseManager.xml` sein, nicht die durchnummerierten einzelnen Dateien. Wenn du die ausgewählt hast, dann poste diese bitte hier.

**Comment by mxalbert** [comment]
Ich habe die `CourseManager.xml` ausgewählt, nicht die `CourseStorageXXXX.xml`. 
[courseManager.zip](https://github.com/yankee42/courseplay-osm-converter/files/3040227/courseManager.zip)

**Comment by yankee42** [comment]
OK, ich sehe das Problem liegt daran, dass du keine Ordner angelegt hast in denen die Kurse abgelegt sind. Das Programm erwartet aber das Ordner existieren. An den Fall habe ich nicht gedacht. Ich bastel einen Fix dafür. Bis der da ist, kannst du einfach einen beliebigen Ordner anlegen (du musst auch nichts rein packen), dann sollte es funktionieren.

**Comment by mxalbert** [comment]
Ok, ja sind halt nicht so viele Kurse. Aber danke.

**Comment by yankee42** [comment]
Fixed in v1.0.1

**Comment by mxalbert** [comment]
@yankee42 Schlechte Nachrichten, der Fehler tritt auf, obwohl ich Ordner erstellt habe und in beiden Versionsnummern.

Ich hänge mal den gesamten Courseplay Ordner an.

[CoursePlay_Courses.zip](https://github.com/yankee42/courseplay-osm-converter/files/3040528/CoursePlay_Courses.zip)

**Comment by yankee42** [comment]
Ich habe mir das angesehen und ich denke ich weiß was das Problem ist, aber es ist eine völlig andere Ursache, deswegen habe ich dafür das neue Ticket #4 aufgemacht. Fix ist unterwegs.
