### ISSUE TITLE
JAVA Fehler bei Konvertierung in OSM

### ISSUE THREAD

**Issue by KarwendelHopper** [yankee42/courseplay-osm-converter#5]
"Courseconvert.JAR" konvertiert meine course xml erst gar nicht. Warum weiß ich nicht. Es gibt eine Fehlermeldung die ich nicht als LOG Datei habe, sondern nur als PNG vom Snippingtool.

https://share-your-photo.com/0b27f183ae/album

Für Hilfe wäre ich sehr dankbar, da ich diese Tool wirklich sehr gerne nutzen würde. 
(Ich m/43 Jahre und wohl nicht mehr ganz so fit mit Java. ;-) )

**Comment by yankee42** [comment]
Mh, merkwürdig, das deutet darauf hin, dass du in einer der course.xml-Dateien Koordinaten hast, die nicht aus drei Werten bestehen. Könntest du deine Kurs-Dateien hier posten (am besten alle in ein zip packen)? Du kannst auch direkt hier im GitHub an einen Kommentar Dateien anhängen und brauchst dann keinen externen Hoster.

**Comment by KarwendelHopper** [comment]
OK. Ich verstehe das richtig das Du meine XML haben willst? Kein Problem. Gib mir 5 min fürs packen und 10 zum "Antwort Button" suchen ... (ZIP oder RAR?)

**Comment by KarwendelHopper** [comment]
> 
> 
> Mh, merkwürdig, das deutet darauf hin, dass du in einer der course.xml-Dateien Koordinaten hast, die nicht aus drei Werten bestehen. Könntest du deine Kurs-Dateien hier posten (am besten alle in ein zip packen)? Du kannst auch direkt hier im GitHub an einen Kommentar Dateien anhängen und brauchst dann keinen externen Hoster.

[courseManager.zip](https://github.com/yankee42/courseplay-osm-converter/files/3049200/courseManager.zip)

**Comment by KarwendelHopper** [comment]
So da isses. Das ist die einzigste die ich fand. Gruß

**Comment by yankee42** [comment]
OK gut Anfang. Du hast echt viele Kurse ;-). Die ganzen courseStorageXXXX.xml bräuchte ich allerdings auch. Die müssten im gleichen Verzeichnis daneben liegen.

**Comment by KarwendelHopper** [comment]
> 
> 
> OK gut Anfang. Du hast echt viele Kurse ;-). Die ganzen courseStorageXXXX.xml bräuchte ich allerdings auch. Die müssten im gleichen Verzeichnis daneben liegen.

[Allexml_im_Ordner_daneben_iss_nix.zip](https://github.com/yankee42/courseplay-osm-converter/files/3049223/Allexml_im_Ordner_daneben_iss_nix.zip)
Alles was im Course Ordner drinn war.

**Comment by yankee42** [comment]
OK komisch, du hast wirklich eine ganze Reihe Kurse, die nur zwei Koordinaten haben und nicht drei. Ich nehme mal an, dass die Höhe fehlt.

Genau genommen betrifft das die folgenden Dateien bei dir:

Datei | Name                                   
--- | ---                                      
courseStorage0004.xml | F6 Abfahrer            
courseStorage0005.xml | ABF6_BHF_Mühle         
courseStorage0011.xml | ABF10_Getreidemuehle   
courseStorage0017.xml | F28_Unkraut_striegel   
courseStorage0018.xml | f13 säen               
courseStorage0019.xml | F27 F26 Pflügen NEU    
courseStorage0025.xml | XF22zuHafenSüd         
courseStorage0026.xml | F28_düngen             
courseStorage0027.xml | F29_düngen             
courseStorage0032.xml | Hof_F1bisF5            
courseStorage0034.xml | F1bisF5_Hof            
courseStorage0036.xml | F20Wiese_Nord          
courseStorage0037.xml | F20_Dreschen           
courseStorage0038.xml | F20_DrescherStroh Kurs 
courseStorage0041.xml | VF23u30zuHof           
courseStorage0043.xml | Hof_BHFmühle_Hof       
courseStorage0044.xml | F4undF5zuF1            
courseStorage0045.xml | HofzuF23u30            
courseStorage0048.xml | F1zuF4undF5            
courseStorage0051.xml | F18_Pflügen            
courseStorage0053.xml | F27Drescher neu        
courseStorage0054.xml | F34 grubbern           
courseStorage0055.xml | F34 säendüngen         
courseStorage0056.xml | F19 Wiese westbisNord  

Am einfachsten wäre es, ich würde die Höhe als Null interpretieren und zurückschreiben. Ich kann das leider nicht testen, aber ich habe mal eine Version für dich gebaut, die dies so tun würde:

[courseconvert.zip](https://github.com/yankee42/courseplay-osm-converter/files/3049262/courseconvert.zip)

Versuch es mal damit, insbesondere ob du nach dem zurückkonvertieren die oben gelisteten Kurse noch verwenden kannst. Vorher unbedingt ein Backup machen! (wobei das hast du ja jetzt in dem Ticket hier ^^)

**Comment by Gadarol** [comment]
Fürs Protokoll wäre übrigens immer hilfreich zu wissen welche Courseplay Version verwendet wurde, als die Kurse erstellt wurden. Alle Kurse, die du vor dem 15.02.2019 eingefahren hast haben nur zwei Koordinaten, danach scheint alles (stichproben) zu passen. Als ob es da mal eine Version gab, die da andere XMLs geschrieben hat.
Das Weglassen der Höhe hat übrigens "nur" zu Folge, dass man gfs. die gelben Kontroll - Dots nicht mehr sehen kann, der Rest sollte dennoch funktionieren :)

**Comment by KarwendelHopper** [comment]
OK: THX...Gib mir paar Stunden. Muss erst Augenpflege betreiben und moregn guck ich :-D Ich mach es mal wie Du sagst. Was die versionen von Cp betrifft kann ich nur sagen...."Jeden 2,6ten Tag das Update gemacht." Aus welcher Version die Kurse sind ...   ? :-D

**Comment by KarwendelHopper** [comment]
Werde es gleich probieren. Die gelisteteten Kurse sind sehr alt. Die stammen eus der CP Version 0008 - 00036 . "Hof_F1bisF5" z.B. (dort muss man auf der Standard Map über die Brücke fahren und im Spiel flutschen die Wegpunkte unter die Brücke. 

EDIT: Nein geht leider nicht. Es kommt zwar keine Fehlermeldung aber er speichert nicht. Öffnen geht, Eingabe der Größe 2048 geht auch aber dann beim speichern wird keine OSM in neuem Ordner erzeugt.

**Comment by KarwendelHopper** [comment]
Ich werde mal die genannten Kurse löschen. Bin mal gespannt.

**Comment by yankee42** [comment]
> EDIT: Nein geht leider nicht. Es kommt zwar keine Fehlermeldung aber er speichert nicht. Öffnen geht, Eingabe der Größe 2048 geht auch aber dann beim speichern wird keine OSM in neuem Ordner erzeugt.

Kam denn eine Fehlermeldung? Kam der "Done"-Dialog? Eins von beiden müsste eigentlich auf jeden Falls passieren. Und wenn "Done" kommt, dann muss auch eine Datei erzeugt worden sein...

**Comment by KarwendelHopper** [comment]
Nein. Done kam nicht. Die Anwendung liesnsich dann auch nichz meht schliessen. Habe die genannten Kurse gelöscht....dann gings

**Comment by yankee42** [comment]
OK, gut, dass du das Problem lösen konntest. Schade, dass wir dann nicht herausgefunden haben ob wir die alten Kurse auch hätten unterstützen können. Immerhin wissen wir jetzt, dass dieser Fehler auf eine ältere Version von Courseplay zurückgeht.

**Comment by KarwendelHopper** [comment]
Ja richtig. Schade aber naja. So muss ich dann wohl auf der Felsbrunn den Weg zu den Feldern 1-5 nochmal fahren... X-)

**Comment by KarwendelHopper** [comment]
Jetzt such ich nur noch die MAP.png fürs Hintergrundbild...Gibts noch einen Tip wo ich die finde?

**Comment by Gadarol** [comment]
Du findest die Datei pda_map_H.dds in der Zip-Datei der Map unter /maps.
Diese dann einfach mit z.B. irfanview oder einem anderen Grafiktool deiner Wahl in z.B. png umwandeln.

**Comment by KarwendelHopper** [comment]
Danke.
