### ISSUE TITLE
Fehlermeldung beim konvertieren in OSM

### ISSUE THREAD

**Issue by GeorgK1988** [yankee42/courseplay-osm-converter#8]
Hallo,
Vorest, Hut ab für den Mod, wirklich genial!!
Aber leider bekomme ich eine Fehlermeldung wenn ich den Kurs in OSM konvertieren will.
- Converter Version 1.0.3
- Courseplay Version 6.01.00163
- Datum ältester Kurs 2.2.19

Danke für die Hilfe!
LG

![2019-04-07 11_10_10-Greenshot](https://user-images.githubusercontent.com/49338248/55681750-47d2b300-592a-11e9-84c4-7c897a0a3a6a.jpg)

**Comment by yankee42** [comment]
Duplicate of #5 
Der Fehler `Cannot parse Position <XX.XX YY.YY>` deutet darauf hin, dass die Datei mit einer älteren Version von Courseplay erstellt wurde, denn in der aktuellen Version hat die Position 3 Werte (height ist dazugekommen).

Du kannst den entsprechenden Kurs natürlich einfach löschen, dann ist das Problem gelöst. Ich hatte allerdings auch [hier eine Testversion erstellt](https://github.com/yankee42/courseplay-osm-converter/files/3049262/courseconvert.zip), die versucht die Kurse trotzdem zu konvertieren. Wenn du möchtest, kannst du es mal mit dieser probieren. Stecke jedoch nicht zu viel Arbeit in Änderungen, bevor du nicht getestet hast, ob du die erzeugte Datei wieder zurückkonvertieren kannst und diese im LS dann nutzbar ist. Und erstelle unbedingt vorher ein Backup der Kurse.

**Comment by GeorgK1988** [comment]
Leider kommt wenn ich die Testversion verwende beim zurückkonvertieren auch eine Fehlermeldung.. 

![2019-04-07 14_23_29-Greenshot](https://user-images.githubusercontent.com/49338248/55683512-dd793d00-5940-11e9-8920-ebc65826c06c.jpg)

Den Kurs löschen würde zwar gehen, aber es sind mehrere Kurse betroffen, will nicht alle löschen müssen.

Lg

**Comment by yankee42** [comment]
Mhh... Könntest du mir den Ordner mit den XML-Dateien von Course.xml hier hochladen? Dann kann ich selber mal schauen was da passiert.

BTW: Wenn so eine Fehlermeldung kommt, dann wird die auch automatisch in die Zwischenablage kopiert. Dann musst du keinen Screenshot machen.

**Comment by GeorgK1988** [comment]
Na klar, kein Problem!

Aa ok, mach ich beim nächsten mal!
[CoursePlay_Courses.zip](https://github.com/yankee42/courseplay-osm-converter/files/3051771/CoursePlay_Courses.zip)

**Comment by yankee42** [comment]
OK, danke. Ich habe jetzt das ZIP heruntergeladen, dann als erstes mit der oben verlinkten Testversion vom Converter die Kurse zu OSM konvertiert und ohne etwas zu ändern dann das erzeugte OSM sofort wieder zurück zu den Kursen. Dabei trat aber kein Fehler auf.

Hattest du irgendwas anders gemacht?

**Comment by yankee42** [comment]
Hier ist nochmal eine neue Preview-Version, die sowohl mit den alten Dateien umgehen können soll, als auch neue Wegpunkte unterstützen sollte. Könntest du mit dieser nochmal testen?

[courseconvert.zip](https://github.com/yankee42/courseplay-osm-converter/files/3055203/courseconvert.zip)

**Comment by GeorgK1988** [comment]
Hallo,
Super Danke! Ich werd es sobald als möglich probieren! Wird aber eher erst am Wochenende sein!
Danke schon mal!!
Find ich super dass du so hilfst!! 
Lg

**Comment by KarwendelHopper** [comment]
Sollte noch jemand Interesse an älteren Versionen von CP haben, einfach melden. (Siehe Bild unten)
![courseplayversionen](https://user-images.githubusercontent.com/49316807/55813689-7e0c6000-5aed-11e9-9284-23908f16ec26.PNG)

**Comment by yankee42** [comment]
Nach Feedback das bisher gekommen ist, habe ich die Änderungen in der oben verlinkten Testversion mittlerweile in v1.0.5. integriert und released. Ich gehe daher davon aus, dass das Problem behoben ist und schließe das Ticket. Gerne freue ich mich trotzdem über euer Feedback ob es wirklich mit 1.0.5. behoben ist.

**Comment by GeorgK1988** [comment]
Hallo,

bin erst jetzt dazu gekommen es zu testen.
Funktioniert jetzt einwandfrei!
Danke für deine Mühe!!

LG und schönes Wochenende!
Georg

Am Do., 11. Apr. 2019 um 23:29 Uhr schrieb Yannik Hampe <
notifications@github.com>:

**Comment by yankee42** [comment]
@GeorgK1988: Vielen Dank für deine Rückmeldung.
